/*************************
 * GPIO PINCTRLMTK File
*************************/

#ifndef __PINCTRL_MTK_MT6580_H
#define __PINCTRL_MTK_MT6580_H

#include <linux/pinctrl/pinctrl.h>
#include "pinctrl-mtk-common.h"

static const struct mtk_desc_pin mtk_pins_mt6595[] = {
    MTK_PIN(
        PINCTRL_PIN(0, "GPIO0"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO0"),
        MTK_FUNCTION(1, "IRDA_PDN"),
        MTK_FUNCTION(2, "I2S1_WS"),
        MTK_FUNCTION(4, "TDD_TMS"),
        MTK_FUNCTION(5, "UTXD0")
    ),
    MTK_PIN(
        PINCTRL_PIN(1, "GPIO1"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO1"),
        MTK_FUNCTION(1, "IRDA_RXD"),
        MTK_FUNCTION(2, "I2S1_BCK"),
        MTK_FUNCTION(3, "SDA4"),
        MTK_FUNCTION(4, "TDD_TCK"),
        MTK_FUNCTION(5, "URXD0")
    ),
    MTK_PIN(
        PINCTRL_PIN(2, "GPIO2"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO2"),
        MTK_FUNCTION(1, "IRDA_TXD"),
        MTK_FUNCTION(2, "I2S1_MCK"),
        MTK_FUNCTION(3, "SCL4"),
        MTK_FUNCTION(4, "TDD_TDI"),
        MTK_FUNCTION(5, "UTXD3")
    ),
    MTK_PIN(
        PINCTRL_PIN(3, "GPIO3"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO3"),
        MTK_FUNCTION(1, "DSI1_TE"),
        MTK_FUNCTION(2, "I2S1_DO_1"),
        MTK_FUNCTION(3, "SDA3"),
        MTK_FUNCTION(4, "TDD_TDO"),
        MTK_FUNCTION(5, "URXD3")
    ),
    MTK_PIN(
        PINCTRL_PIN(4, "GPIO4"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO4"),
        MTK_FUNCTION(1, "DISP_PWM1"),
        MTK_FUNCTION(2, "I2S1_DO_2"),
        MTK_FUNCTION(3, "SCL3"),
        MTK_FUNCTION(4, "TDD_TRSTN")
    ),
    MTK_PIN(
        PINCTRL_PIN(5, "GPIO5"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO5"),
        MTK_FUNCTION(1, "PCM1_CLK"),
        MTK_FUNCTION(2, "I2S2_WS"),
        MTK_FUNCTION(3, "SPI_CK_3_"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TMS"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TMS")
    ),
    MTK_PIN(
        PINCTRL_PIN(6, "GPIO6"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO6"),
        MTK_FUNCTION(1, "PCM1_SYNC"),
        MTK_FUNCTION(2, "I2S2_BCK"),
        MTK_FUNCTION(3, "SPI_MI_3_"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TCK"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TCK")
    ),
    MTK_PIN(
        PINCTRL_PIN(7, "GPIO7"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO7"),
        MTK_FUNCTION(1, "PCM1_DI"),
        MTK_FUNCTION(2, "I2S2_DI_1"),
        MTK_FUNCTION(3, "SPI_MO_3_"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TDI"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TDI")
    ),
    MTK_PIN(
        PINCTRL_PIN(8, "GPIO8"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO8"),
        MTK_FUNCTION(1, "PCM1_DO"),
        MTK_FUNCTION(2, "I2S2_DI_2"),
        MTK_FUNCTION(3, "SPI_CS_3_"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TDO"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TDO")
    ),
    MTK_PIN(
        PINCTRL_PIN(9, "GPIO9"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO9"),
        MTK_FUNCTION(1, "USB_DRVVBUS"),
        MTK_FUNCTION(2, "I2S2_MCK"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TRST"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TRST")
    ),
    MTK_PIN(
        PINCTRL_PIN(10, "GPIO10"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"),
        MTK_FUNCTION(2, "I2S0_WS")
    ),
    MTK_PIN(
        PINCTRL_PIN(11, "GPIO11"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"),
        MTK_FUNCTION(2, "I2S0_BCK")
    ),
    MTK_PIN(
        PINCTRL_PIN(12, "GPIO12"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"),
        MTK_FUNCTION(2, "I2S0_MCK"),
        MTK_FUNCTION(7, "DBG_MON_B_32_")
    ),
    MTK_PIN(
        PINCTRL_PIN(13, "GPIO13"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"),
        MTK_FUNCTION(2, "I2S0_DO"),
        MTK_FUNCTION(7, "DBG_MON_C_0_")
    ),
    MTK_PIN(
        PINCTRL_PIN(14, "GPIO14"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"),
        MTK_FUNCTION(2, "I2S0_DI"),
        MTK_FUNCTION(3, "DISP_PWM1"),
        MTK_FUNCTION(4, "PWM4"),
        MTK_FUNCTION(5, "IRDA_RXD"),
        MTK_FUNCTION(6, "I2S1_BCK"),
        MTK_FUNCTION(7, "DBG_MON_C_1_")
    ),
    MTK_PIN(
        PINCTRL_PIN(15, "GPIO15"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"),
        MTK_FUNCTION(2, "DSI1_TE"),
        MTK_FUNCTION(3, "USB_DRVVBUS"),
        MTK_FUNCTION(4, "PWM5"),
        MTK_FUNCTION(5, "IRDA_TXD"),
        MTK_FUNCTION(6, "I2S1_MCK")
    ),
    MTK_PIN(
        PINCTRL_PIN(16, "GPIO16"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"),
        MTK_FUNCTION(1, "IDDIG"),
        MTK_FUNCTION(2, "FLASH"),
        MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
        MTK_FUNCTION(4, "PWM5")
    ),
    MTK_PIN(
        PINCTRL_PIN(17, "GPIO17"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"),
        MTK_FUNCTION(1, "SIM1_SCLK"),
        MTK_FUNCTION(2, "SIM2_SCLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(18, "GPIO18"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"),
        MTK_FUNCTION(1, "SIM1_SRST"),
        MTK_FUNCTION(2, "SIM2_SRST")
    ),
    MTK_PIN(
        PINCTRL_PIN(19, "GPIO19"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"),
        MTK_FUNCTION(1, "SIM1_SDAT"),
        MTK_FUNCTION(2, "SIM2_SDAT")
    ),
    MTK_PIN(
        PINCTRL_PIN(20, "GPIO20"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO20"),
        MTK_FUNCTION(1, "SIM2_SCLK"),
        MTK_FUNCTION(2, "SIM1_SCLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(21, "GPIO21"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO21"),
        MTK_FUNCTION(1, "SIM2_SRST"),
        MTK_FUNCTION(2, "SIM1_SRST")
    ),
    MTK_PIN(
        PINCTRL_PIN(22, "GPIO22"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO22"),
        MTK_FUNCTION(1, "SIM2_SDAT"),
        MTK_FUNCTION(2, "SIM1_SDAT")
    ),
    MTK_PIN(
        PINCTRL_PIN(23, "GPIO23"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO23"),
        MTK_FUNCTION(1, "MSDC3_DAT0")
    ),
    MTK_PIN(
        PINCTRL_PIN(24, "GPIO24"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO24"),
        MTK_FUNCTION(1, "MSDC3_DAT1")
    ),
    MTK_PIN(
        PINCTRL_PIN(25, "GPIO25"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO25"),
        MTK_FUNCTION(1, "MSDC3_DAT2")
    ),
    MTK_PIN(
        PINCTRL_PIN(26, "GPIO26"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO26"),
        MTK_FUNCTION(1, "MSDC3_DAT3")
    ),
    MTK_PIN(
        PINCTRL_PIN(27, "GPIO27"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO27"),
        MTK_FUNCTION(1, "MSDC3_CLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(28, "GPIO28"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO28"),
        MTK_FUNCTION(1, "MSDC3_CMD")
    ),
    MTK_PIN(
        PINCTRL_PIN(29, "GPIO29"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO29"),
        MTK_FUNCTION(1, "PTA_RXD"),
        MTK_FUNCTION(2, "UCTS2")
    ),
    MTK_PIN(
        PINCTRL_PIN(30, "GPIO30"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO30"),
        MTK_FUNCTION(1, "PTA_TXD"),
        MTK_FUNCTION(2, "URTS2")
    ),
    MTK_PIN(
        PINCTRL_PIN(31, "GPIO31"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO31"),
        MTK_FUNCTION(1, "URXD2"),
        MTK_FUNCTION(2, "UTXD2")
    ),
    MTK_PIN(
        PINCTRL_PIN(32, "GPIO32"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO32"),
        MTK_FUNCTION(1, "UTXD2"),
        MTK_FUNCTION(2, "URXD2")
    ),
    MTK_PIN(
        PINCTRL_PIN(33, "GPIO33"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO33"),
        MTK_FUNCTION(1, "MRG_CLK"),
        MTK_FUNCTION(2, "PCM0_CLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(34, "GPIO34"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO34"),
        MTK_FUNCTION(1, "MRG_DI"),
        MTK_FUNCTION(2, "PCM0_DI")
    ),
    MTK_PIN(
        PINCTRL_PIN(35, "GPIO35"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO35"),
        MTK_FUNCTION(1, "MRG_DO"),
        MTK_FUNCTION(2, "PCM0_DO")
    ),
    MTK_PIN(
        PINCTRL_PIN(36, "GPIO36"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO36"),
        MTK_FUNCTION(1, "MRG_SYNC"),
        MTK_FUNCTION(2, "PCM0_SYNC")
    ),
    MTK_PIN(
        PINCTRL_PIN(37, "GPIO37"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO37"),
        MTK_FUNCTION(1, "GPS_SYNC")
    ),
    MTK_PIN(
        PINCTRL_PIN(38, "GPIO38"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO38"),
        MTK_FUNCTION(1, "DAIRSTB")
    ),
    MTK_PIN(
        PINCTRL_PIN(39, "GPIO39"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO39"),
        MTK_FUNCTION(1, "CM2MCLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(40, "GPIO40"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO40"),
        MTK_FUNCTION(1, "CM3MCLK"),
        MTK_FUNCTION(2, "IRDA_PDN"),
        MTK_FUNCTION(3, "PWM6"),
        MTK_FUNCTION(4, "I2S1_WS")
    ),
    MTK_PIN(
        PINCTRL_PIN(41, "GPIO41"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO41"),
        MTK_FUNCTION(1, "CMPCLK"),
        MTK_FUNCTION(2, "CMCSK"),
        MTK_FUNCTION(3, "FLASH")
    ),
    MTK_PIN(
        PINCTRL_PIN(42, "GPIO42"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO42"),
        MTK_FUNCTION(1, "CMMCLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(43, "GPIO43"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO43"),
        MTK_FUNCTION(1, "SDA2")
    ),
    MTK_PIN(
        PINCTRL_PIN(44, "GPIO44"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO44"),
        MTK_FUNCTION(1, "SCL2")
    ),
    MTK_PIN(
        PINCTRL_PIN(45, "GPIO45"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO45"),
        MTK_FUNCTION(1, "SDA0")
    ),
    MTK_PIN(
        PINCTRL_PIN(46, "GPIO46"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO46"),
        MTK_FUNCTION(1, "SCL0")
    ),
    MTK_PIN(
        PINCTRL_PIN(47, "GPIO47"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO47"),
        MTK_FUNCTION(1, "BPI_BUS0"),
        MTK_FUNCTION(7, "DBG_MON_C_2_")
    ),
    MTK_PIN(
        PINCTRL_PIN(48, "GPIO48"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO48"),
        MTK_FUNCTION(1, "BPI_BUS1"),
        MTK_FUNCTION(7, "DBG_MON_C_3_")
    ),
    MTK_PIN(
        PINCTRL_PIN(49, "GPIO49"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO49"),
        MTK_FUNCTION(1, "BPI_BUS2"),
        MTK_FUNCTION(7, "DBG_MON_C_4_")
    ),
    MTK_PIN(
        PINCTRL_PIN(50, "GPIO50"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO50"),
        MTK_FUNCTION(1, "BPI_BUS3"),
        MTK_FUNCTION(7, "DBG_MON_C_5_")
    ),
    MTK_PIN(
        PINCTRL_PIN(51, "GPIO51"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO51"),
        MTK_FUNCTION(1, "BPI_BUS4"),
        MTK_FUNCTION(7, "DBG_MON_C_6_")
    ),
    MTK_PIN(
        PINCTRL_PIN(52, "GPIO52"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO52"),
        MTK_FUNCTION(1, "BPI_BUS5"),
        MTK_FUNCTION(7, "DBG_MON_C_7_")
    ),
    MTK_PIN(
        PINCTRL_PIN(53, "GPIO53"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO53"),
        MTK_FUNCTION(1, "BPI_BUS6"),
        MTK_FUNCTION(7, "DBG_MON_C_8_")
    ),
    MTK_PIN(
        PINCTRL_PIN(54, "GPIO54"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO54"),
        MTK_FUNCTION(1, "BPI_BUS7"),
        MTK_FUNCTION(7, "DBG_MON_C_9_")
    ),
    MTK_PIN(
        PINCTRL_PIN(55, "GPIO55"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO55"),
        MTK_FUNCTION(1, "BPI_BUS8"),
        MTK_FUNCTION(7, "DBG_MON_C_10_")
    ),
    MTK_PIN(
        PINCTRL_PIN(56, "GPIO56"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO56"),
        MTK_FUNCTION(1, "BPI_BUS9"),
        MTK_FUNCTION(7, "DBG_MON_C_11_")
    ),
    MTK_PIN(
        PINCTRL_PIN(57, "GPIO57"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO57"),
        MTK_FUNCTION(1, "BPI_BUS10"),
        MTK_FUNCTION(7, "DBG_MON_C_12_")
    ),
    MTK_PIN(
        PINCTRL_PIN(58, "GPIO58"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO58"),
        MTK_FUNCTION(1, "BPI_BUS11"),
        MTK_FUNCTION(7, "DBG_MON_C_13_")
    ),
    MTK_PIN(
        PINCTRL_PIN(59, "GPIO59"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO59"),
        MTK_FUNCTION(1, "BPI_BUS12"),
        MTK_FUNCTION(7, "DBG_MON_C_14_")
    ),
    MTK_PIN(
        PINCTRL_PIN(60, "GPIO60"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO60"),
        MTK_FUNCTION(1, "BPI_BUS13"),
        MTK_FUNCTION(7, "DBG_MON_C_15_")
    ),
    MTK_PIN(
        PINCTRL_PIN(61, "GPIO61"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO61"),
        MTK_FUNCTION(1, "BPI_BUS14"),
        MTK_FUNCTION(7, "DBG_MON_C_16_")
    ),
    MTK_PIN(
        PINCTRL_PIN(62, "GPIO62"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO62"),
        MTK_FUNCTION(1, "RFIC1_BSI_CK"),
        MTK_FUNCTION(7, "DBG_MON_C_17_")
    ),
    MTK_PIN(
        PINCTRL_PIN(63, "GPIO63"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO63"),
        MTK_FUNCTION(1, "RFIC1_BSI_D0"),
        MTK_FUNCTION(7, "DBG_MON_C_18_")
    ),
    MTK_PIN(
        PINCTRL_PIN(64, "GPIO64"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO64"),
        MTK_FUNCTION(1, "RFIC1_BSI_D1"),
        MTK_FUNCTION(7, "DBG_MON_C_19_")
    ),
    MTK_PIN(
        PINCTRL_PIN(65, "GPIO65"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO65"),
        MTK_FUNCTION(1, "RFIC1_BSI_D2"),
        MTK_FUNCTION(7, "DBG_MON_C_20_")
    ),
    MTK_PIN(
        PINCTRL_PIN(66, "GPIO66"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO66"),
        MTK_FUNCTION(1, "RFIC1_BSI_CS")
    ),
    MTK_PIN(
        PINCTRL_PIN(67, "GPIO67"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO67"),
        MTK_FUNCTION(1, "TD_TXBPI")
    ),
    MTK_PIN(
        PINCTRL_PIN(68, "GPIO68"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO68"),
        MTK_FUNCTION(1, "RFIC0_BSI_CK")
    ),
    MTK_PIN(
        PINCTRL_PIN(69, "GPIO69"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO69"),
        MTK_FUNCTION(1, "RFIC0_BSI_D0")
    ),
    MTK_PIN(
        PINCTRL_PIN(70, "GPIO70"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO70"),
        MTK_FUNCTION(1, "RFIC0_BSI_D1")
    ),
    MTK_PIN(
        PINCTRL_PIN(71, "GPIO71"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO71"),
        MTK_FUNCTION(1, "RFIC0_BSI_D2")
    ),
    MTK_PIN(
        PINCTRL_PIN(72, "GPIO72"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO72"),
        MTK_FUNCTION(1, "RFIC0_BSI_CS")
    ),
    MTK_PIN(
        PINCTRL_PIN(73, "GPIO73"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO73"),
        MTK_FUNCTION(1, "MISC_BSI_DO")
    ),
    MTK_PIN(
        PINCTRL_PIN(74, "GPIO74"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO74"),
        MTK_FUNCTION(1, "MISC_BSI_CK")
    ),
    MTK_PIN(
        PINCTRL_PIN(75, "GPIO75"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO75"),
        MTK_FUNCTION(1, "MISC_BSI_CS0B"),
        MTK_FUNCTION(2, "MIPI1_SCLK")
    ),
    MTK_PIN(
        PINCTRL_PIN(76, "GPIO76"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO76"),
        MTK_FUNCTION(1, "MISC_BSI_CS1B")
    ),
    MTK_PIN(
        PINCTRL_PIN(77, "GPIO77"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO77"),
        MTK_FUNCTION(1, "MISC_BSI_DI"),
        MTK_FUNCTION(2, "MIPI1_SDATA")
    ),
    MTK_PIN(
        PINCTRL_PIN(78, "GPIO78"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO78"),
        MTK_FUNCTION(1, "LTE_TXBPI")
    ),
    MTK_PIN(
        PINCTRL_PIN(79, "GPIO79"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO79"),
        MTK_FUNCTION(1, "BPI_BUS15")
    ),
    MTK_PIN(
        PINCTRL_PIN(80, "GPIO80"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO80"),
        MTK_FUNCTION(1, "BPI_BUS16")
    ),
    MTK_PIN(
        PINCTRL_PIN(81, "GPIO81"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO81"),
        MTK_FUNCTION(1, "BPI_BUS17")
    ),
    MTK_PIN(
        PINCTRL_PIN(82, "GPIO82"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO82"),
        MTK_FUNCTION(1, "BPI_BUS18")
    ),
    MTK_PIN(
        PINCTRL_PIN(83, "GPIO83"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO83"),
        MTK_FUNCTION(1, "BPI_BUS19")
    ),
    MTK_PIN(
        PINCTRL_PIN(84, "GPIO84"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO84"),
        MTK_FUNCTION(1, "BPI_BUS20")
    ),
    MTK_PIN(
        PINCTRL_PIN(85, "GPIO85"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO85"),
        MTK_FUNCTION(1, "BPI_BUS21")
    ),
    MTK_PIN(
        PINCTRL_PIN(86, "GPIO86"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO86"),
        MTK_FUNCTION(1, "BPI_BUS22")
    ),
    MTK_PIN(
        PINCTRL_PIN(87, "GPIO87"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO87"),
        MTK_FUNCTION(1, "BPI_BUS23")
    ),
    MTK_PIN(
        PINCTRL_PIN(88, "GPIO88"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO88"),
        MTK_FUNCTION(1, "BPI_BUS24")
    ),
    MTK_PIN(
        PINCTRL_PIN(89, "GPIO89"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO89"),
        MTK_FUNCTION(1, "BPI_BUS25")
    ),
    MTK_PIN(
        PINCTRL_PIN(90, "GPIO90"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO90"),
        MTK_FUNCTION(1, "BPI_BUS26")
    ),
    MTK_PIN(
        PINCTRL_PIN(91, "GPIO91"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO91"),
        MTK_FUNCTION(1, "BPI_BUS27")
    ),
    MTK_PIN(
        PINCTRL_PIN(92, "GPIO92"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO92"),
        MTK_FUNCTION(1, "PCM1_CLK"),
        MTK_FUNCTION(2, "I2S0_BCK"),
        MTK_FUNCTION(3, "NLD6"),
        MTK_FUNCTION(7, "DBG_MON_C_21_")
    ),
    MTK_PIN(
        PINCTRL_PIN(93, "GPIO93"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO93"),
        MTK_FUNCTION(1, "PCM1_SYNC"),
        MTK_FUNCTION(2, "I2S0_WS"),
        MTK_FUNCTION(3, "NLD7"),
        MTK_FUNCTION(7, "DBG_MON_C_22_")
    ),
    MTK_PIN(
        PINCTRL_PIN(94, "GPIO94"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO94"),
        MTK_FUNCTION(1, "PCM1_DI"),
        MTK_FUNCTION(2, "I2S0_DI"),
        MTK_FUNCTION(3, "NREB"),
        MTK_FUNCTION(7, "DBG_MON_C_23_")
    ),
    MTK_PIN(
        PINCTRL_PIN(95, "GPIO95"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO95"),
        MTK_FUNCTION(1, "PCM1_DO"),
        MTK_FUNCTION(2, "I2S0_DO"),
        MTK_FUNCTION(3, "NRNB0"),
        MTK_FUNCTION(7, "DBG_MON_C_24_")
    ),
    MTK_PIN(
        PINCTRL_PIN(96, "GPIO96"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO96"),
        MTK_FUNCTION(1, "URXD1"),
        MTK_FUNCTION(2, "UTXD1"),
        MTK_FUNCTION(3, "NWEB"),
        MTK_FUNCTION(7, "DBG_MON_C_25_")
    ),
    MTK_PIN(
        PINCTRL_PIN(97, "GPIO97"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO97"),
        MTK_FUNCTION(1, "UTXD1"),
        MTK_FUNCTION(2, "URXD1"),
        MTK_FUNCTION(3, "NCEB0"),
        MTK_FUNCTION(7, "DBG_MON_C_26_")
    ),
    MTK_PIN(
        PINCTRL_PIN(98, "GPIO98"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO98"),
        MTK_FUNCTION(1, "URTS1"),
        MTK_FUNCTION(2, "UCTS1"),
        MTK_FUNCTION(3, "NALE"),
        MTK_FUNCTION(7, "DBG_MON_C_27_")
    ),
    MTK_PIN(
        PINCTRL_PIN(99, "GPIO99"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO99"),
        MTK_FUNCTION(1, "UCTS1"),
        MTK_FUNCTION(2, "URTS1"),
        MTK_FUNCTION(3, "NCLE"),
        MTK_FUNCTION(7, "DBG_MON_C_28_")
    ),
    MTK_PIN(
        PINCTRL_PIN(100, "GPIO100"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"0),
        MTK_FUNCTION(1, "MSDC2_DAT0"),
        MTK_FUNCTION(2, "URXD1"),
        MTK_FUNCTION(3, "USB_DRVVBUS"),
        MTK_FUNCTION(4, "SDA4"),
        MTK_FUNCTION(7, "DBG_MON_C_29_")
    ),
    MTK_PIN(
        PINCTRL_PIN(101, "GPIO101"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"1),
        MTK_FUNCTION(1, "MSDC2_DAT1"),
        MTK_FUNCTION(2, "UTXD1"),
        MTK_FUNCTION(4, "SCL4"),
        MTK_FUNCTION(7, "DBG_MON_C_30_")
    ),
    MTK_PIN(
        PINCTRL_PIN(102, "GPIO102"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"2),
        MTK_FUNCTION(1, "MSDC2_DAT2"),
        MTK_FUNCTION(2, "URTS1"),
        MTK_FUNCTION(3, "UTXD0"),
        MTK_FUNCTION(5, "PWM0"),
        MTK_FUNCTION(6, "SPI_CK_1_")
    ),
    MTK_PIN(
        PINCTRL_PIN(103, "GPIO103"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"3),
        MTK_FUNCTION(1, "MSDC2_DAT3"),
        MTK_FUNCTION(2, "UCTS1"),
        MTK_FUNCTION(3, "URXD0"),
        MTK_FUNCTION(5, "PWM1"),
        MTK_FUNCTION(6, "SPI_MI_1_")
    ),
    MTK_PIN(
        PINCTRL_PIN(104, "GPIO104"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"4),
        MTK_FUNCTION(1, "MSDC2_CLK"),
        MTK_FUNCTION(2, "NLD4"),
        MTK_FUNCTION(3, "UTXD3"),
        MTK_FUNCTION(4, "SDA3"),
        MTK_FUNCTION(5, "PWM2"),
        MTK_FUNCTION(6, "SPI_MO_1_"),
        MTK_FUNCTION(7, "DBG_MON_C_31_")
    ),
    MTK_PIN(
        PINCTRL_PIN(105, "GPIO105"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"5),
        MTK_FUNCTION(1, "MSDC2_CMD"),
        MTK_FUNCTION(2, "NLD5"),
        MTK_FUNCTION(3, "URXD3"),
        MTK_FUNCTION(4, "SCL3"),
        MTK_FUNCTION(5, "PWM3"),
        MTK_FUNCTION(6, "SPI_CS_1_"),
        MTK_FUNCTION(7, "DBG_MON_C_32_")
    ),
    MTK_PIN(
        PINCTRL_PIN(106, "GPIO106"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"6),
        MTK_FUNCTION(1, "LCM_RST")
    ),
    MTK_PIN(
        PINCTRL_PIN(107, "GPIO107"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"7),
        MTK_FUNCTION(1, "DSI_TE")
    ),
    MTK_PIN(
        PINCTRL_PIN(108, "GPIO108"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"8),
        MTK_FUNCTION(1, "JTMS"),
        MTK_FUNCTION(2, "MFG_JTAG_TMS"),
        MTK_FUNCTION(3, "TDD_TMS"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TMS"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TMS"),
        MTK_FUNCTION(6, "DFD_TMS")
    ),
    MTK_PIN(
        PINCTRL_PIN(109, "GPIO109"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO10"9),
        MTK_FUNCTION(1, "JTCK"),
        MTK_FUNCTION(2, "MFG_JTAG_TCK"),
        MTK_FUNCTION(3, "TDD_TCK"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TCK"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TCK"),
        MTK_FUNCTION(6, "DFD_TCK")
    ),
    MTK_PIN(
        PINCTRL_PIN(110, "GPIO110"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"0),
        MTK_FUNCTION(1, "JTDI"),
        MTK_FUNCTION(2, "MFG_JTAG_TDI"),
        MTK_FUNCTION(3, "TDD_TDI"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TDI"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TDI"),
        MTK_FUNCTION(6, "DFD_TDI")
    ),
    MTK_PIN(
        PINCTRL_PIN(111, "GPIO111"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"1),
        MTK_FUNCTION(1, "JTDO"),
        MTK_FUNCTION(2, "MFG_JTAG_TDO"),
        MTK_FUNCTION(3, "TDD_TDO"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TDO"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TDO"),
        MTK_FUNCTION(6, "DFD_TDO")
    ),
    MTK_PIN(
        PINCTRL_PIN(112, "GPIO112"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"2),
        MTK_FUNCTION(1, "JTRST_B"),
        MTK_FUNCTION(2, "MFG_JTAG_TRSTN"),
        MTK_FUNCTION(3, "TDD_TRSTN"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TRST"),
        MTK_FUNCTION(5, "AP_MD32_JTAG_TRST"),
        MTK_FUNCTION(6, "DFD_NTRST")
    ),
    MTK_PIN(
        PINCTRL_PIN(113, "GPIO113"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"3),
        MTK_FUNCTION(1, "URXD0"),
        MTK_FUNCTION(2, "UTXD0"),
        MTK_FUNCTION(3, "MD_URXD"),
        MTK_FUNCTION(4, "LTE_URXD"),
        MTK_FUNCTION(5, "TDD_TXD"),
        MTK_FUNCTION(6, "I2S2_WS"),
        MTK_FUNCTION(7, "DBG_MON_A_0_")
    ),
    MTK_PIN(
        PINCTRL_PIN(114, "GPIO114"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"4),
        MTK_FUNCTION(1, "UTXD0"),
        MTK_FUNCTION(2, "URXD0"),
        MTK_FUNCTION(3, "MD_UTXD"),
        MTK_FUNCTION(4, "LTE_UTXD"),
        MTK_FUNCTION(5, "TDD_TXD"),
        MTK_FUNCTION(6, "I2S2_BCK"),
        MTK_FUNCTION(7, "DBG_MON_A_1_")
    ),
    MTK_PIN(
        PINCTRL_PIN(115, "GPIO115"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"5),
        MTK_FUNCTION(1, "URTS0"),
        MTK_FUNCTION(2, "UCTS0"),
        MTK_FUNCTION(3, "MD_URXD"),
        MTK_FUNCTION(4, "LTE_URXD"),
        MTK_FUNCTION(5, "TDD_TXD"),
        MTK_FUNCTION(6, "I2S2_MCK"),
        MTK_FUNCTION(7, "DBG_MON_A_2_")
    ),
    MTK_PIN(
        PINCTRL_PIN(116, "GPIO116"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"6),
        MTK_FUNCTION(1, "UCTS0"),
        MTK_FUNCTION(2, "URTS0"),
        MTK_FUNCTION(3, "MD_UTXD"),
        MTK_FUNCTION(4, "LTE_UTXD"),
        MTK_FUNCTION(5, "TDD_TXD"),
        MTK_FUNCTION(6, "I2S2_DI_1"),
        MTK_FUNCTION(7, "DBG_MON_A_3_")
    ),
    MTK_PIN(
        PINCTRL_PIN(117, "GPIO117"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"7),
        MTK_FUNCTION(1, "URXD3"),
        MTK_FUNCTION(2, "UTXD3"),
        MTK_FUNCTION(3, "MD_URXD"),
        MTK_FUNCTION(4, "LTE_URXD"),
        MTK_FUNCTION(5, "TDD_TXD"),
        MTK_FUNCTION(7, "DBG_MON_A_9_")
    ),
    MTK_PIN(
        PINCTRL_PIN(118, "GPIO118"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"8),
        MTK_FUNCTION(1, "UTXD3"),
        MTK_FUNCTION(2, "URXD3"),
        MTK_FUNCTION(3, "MD_UTXD"),
        MTK_FUNCTION(4, "LTE_UTXD"),
        MTK_FUNCTION(5, "TDD_TXD"),
        MTK_FUNCTION(7, "DBG_MON_A_10_")
    ),
    MTK_PIN(
        PINCTRL_PIN(119, "GPIO119"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO11"9),
        MTK_FUNCTION(1, "KROW0"),
        MTK_FUNCTION(7, "DBG_MON_A_11_")
    ),
    MTK_PIN(
        PINCTRL_PIN(120, "GPIO120"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"0),
        MTK_FUNCTION(1, "KROW1"),
        MTK_FUNCTION(3, "PWM6"),
        MTK_FUNCTION(7, "DBG_MON_A_12_")
    ),
    MTK_PIN(
        PINCTRL_PIN(121, "GPIO121"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"1),
        MTK_FUNCTION(1, "KROW2"),
        MTK_FUNCTION(2, "IRDA_PDN"),
        MTK_FUNCTION(3, "I2S1_DO_1"),
        MTK_FUNCTION(4, "USB_DRVVBUS"),
        MTK_FUNCTION(5, "SPI_CK_2_"),
        MTK_FUNCTION(6, "PWM4"),
        MTK_FUNCTION(7, "DBG_MON_A_13_")
    ),
    MTK_PIN(
        PINCTRL_PIN(122, "GPIO122"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"2),
        MTK_FUNCTION(1, "KCOL0"),
        MTK_FUNCTION(7, "DBG_MON_A_14_")
    ),
    MTK_PIN(
        PINCTRL_PIN(123, "GPIO123"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"3),
        MTK_FUNCTION(1, "KCOL1"),
        MTK_FUNCTION(2, "IRDA_RXD"),
        MTK_FUNCTION(3, "I2S2_DI_2"),
        MTK_FUNCTION(4, "PWM5"),
        MTK_FUNCTION(7, "DBG_MON_A_15_")
    ),
    MTK_PIN(
        PINCTRL_PIN(124, "GPIO124"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"4),
        MTK_FUNCTION(1, "KCOL2"),
        MTK_FUNCTION(2, "IRDA_TXD"),
        MTK_FUNCTION(3, "I2S1_DO_2"),
        MTK_FUNCTION(4, "USB_DRVVBUS"),
        MTK_FUNCTION(5, "SPI_MI_2_"),
        MTK_FUNCTION(6, "PWM3"),
        MTK_FUNCTION(7, "DBG_MON_A_16_")
    ),
    MTK_PIN(
        PINCTRL_PIN(125, "GPIO125"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"5),
        MTK_FUNCTION(1, "SDA1")
    ),
    MTK_PIN(
        PINCTRL_PIN(126, "GPIO126"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"6),
        MTK_FUNCTION(1, "SCL1")
    ),
    MTK_PIN(
        PINCTRL_PIN(127, "GPIO127"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"7),
        MTK_FUNCTION(1, "MD_EINT1"),
        MTK_FUNCTION(2, "DISP_PWM1"),
        MTK_FUNCTION(3, "SPI_MO_2_")
    ),
    MTK_PIN(
        PINCTRL_PIN(128, "GPIO128"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"8),
        MTK_FUNCTION(1, "MD_EINT2"),
        MTK_FUNCTION(2, "DSI1_TE"),
        MTK_FUNCTION(3, "SPI_CS_2_")
    ),
    MTK_PIN(
        PINCTRL_PIN(129, "GPIO129"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO12"9),
        MTK_FUNCTION(1, "I2S3_WS"),
        MTK_FUNCTION(2, "I2S2_WS"),
        MTK_FUNCTION(3, "PWM0"),
        MTK_FUNCTION(7, "DBG_MON_A_17_")
    ),
    MTK_PIN(
        PINCTRL_PIN(130, "GPIO130"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"0),
        MTK_FUNCTION(1, "I2S3_BCK"),
        MTK_FUNCTION(2, "I2S2_BCK"),
        MTK_FUNCTION(3, "PWM1"),
        MTK_FUNCTION(7, "DBG_MON_A_18_")
    ),
    MTK_PIN(
        PINCTRL_PIN(131, "GPIO131"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"1),
        MTK_FUNCTION(1, "I2S3_MCK"),
        MTK_FUNCTION(2, "I2S2_MCK"),
        MTK_FUNCTION(3, "PWM2"),
        MTK_FUNCTION(7, "DBG_MON_A_19_")
    ),
    MTK_PIN(
        PINCTRL_PIN(132, "GPIO132"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"2),
        MTK_FUNCTION(1, "I2S3_DO_1"),
        MTK_FUNCTION(2, "I2S2_DI_1"),
        MTK_FUNCTION(3, "PWM3"),
        MTK_FUNCTION(7, "DBG_MON_A_20_")
    ),
    MTK_PIN(
        PINCTRL_PIN(133, "GPIO133"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"3),
        MTK_FUNCTION(1, "I2S3_DO_2"),
        MTK_FUNCTION(2, "I2S2_DI_2"),
        MTK_FUNCTION(3, "PWM4"),
        MTK_FUNCTION(7, "DBG_MON_A_21_")
    ),
    MTK_PIN(
        PINCTRL_PIN(134, "GPIO134"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"4),
        MTK_FUNCTION(1, "I2S3_DO_3"),
        MTK_FUNCTION(2, "DISP_PWM1"),
        MTK_FUNCTION(3, "I2S1_DO_1"),
        MTK_FUNCTION(4, "PWM5"),
        MTK_FUNCTION(7, "DBG_MON_A_22_")
    ),
    MTK_PIN(
        PINCTRL_PIN(135, "GPIO135"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"5),
        MTK_FUNCTION(1, "I2S3_DO_4"),
        MTK_FUNCTION(2, "DSI1_TE"),
        MTK_FUNCTION(3, "I2S1_DO_2"),
        MTK_FUNCTION(4, "PWM6"),
        MTK_FUNCTION(7, "DBG_MON_A_23_")
    ),
    MTK_PIN(
        PINCTRL_PIN(136, "GPIO136"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"6),
        MTK_FUNCTION(1, "SDA3")
    ),
    MTK_PIN(
        PINCTRL_PIN(137, "GPIO137"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"7),
        MTK_FUNCTION(1, "SCL3")
    ),
    MTK_PIN(
        PINCTRL_PIN(138, "GPIO138"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"8),
        MTK_FUNCTION(1, "DPI_CK"),
        MTK_FUNCTION(2, "NLD6"),
        MTK_FUNCTION(3, "UTXD0"),
        MTK_FUNCTION(4, "USB_DRVVBUS"),
        MTK_FUNCTION(5, "IRDA_PDN"),
        MTK_FUNCTION(7, "DBG_MON_A_24_")
    ),
    MTK_PIN(
        PINCTRL_PIN(139, "GPIO139"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO13"9),
        MTK_FUNCTION(1, "DPI_DE"),
        MTK_FUNCTION(2, "NLD7"),
        MTK_FUNCTION(3, "URXD0"),
        MTK_FUNCTION(4, "MD_UTXD"),
        MTK_FUNCTION(5, "IRDA_RXD"),
        MTK_FUNCTION(7, "DBG_MON_A_25_")
    ),
    MTK_PIN(
        PINCTRL_PIN(140, "GPIO140"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"0),
        MTK_FUNCTION(1, "DPI_D0"),
        MTK_FUNCTION(2, "NREB"),
        MTK_FUNCTION(3, "UCTS0"),
        MTK_FUNCTION(4, "MD_URXD"),
        MTK_FUNCTION(5, "IRDA_TXD"),
        MTK_FUNCTION(7, "DBG_MON_A_26_")
    ),
    MTK_PIN(
        PINCTRL_PIN(141, "GPIO141"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"1),
        MTK_FUNCTION(1, "DPI_D1"),
        MTK_FUNCTION(2, "NRNB0"),
        MTK_FUNCTION(3, "URTS0"),
        MTK_FUNCTION(4, "LTE_UTXD"),
        MTK_FUNCTION(5, "I2S2_WS"),
        MTK_FUNCTION(7, "DBG_MON_A_27_")
    ),
    MTK_PIN(
        PINCTRL_PIN(142, "GPIO142"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"2),
        MTK_FUNCTION(1, "DPI_D2"),
        MTK_FUNCTION(2, "NWEB"),
        MTK_FUNCTION(3, "UTXD1"),
        MTK_FUNCTION(4, "LTE_URXD"),
        MTK_FUNCTION(5, "I2S2_BCK"),
        MTK_FUNCTION(7, "DBG_MON_A_28_")
    ),
    MTK_PIN(
        PINCTRL_PIN(143, "GPIO143"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"3),
        MTK_FUNCTION(1, "DPI_D3"),
        MTK_FUNCTION(2, "NCEB0"),
        MTK_FUNCTION(3, "URXD1"),
        MTK_FUNCTION(4, "TDD_TXD"),
        MTK_FUNCTION(5, "I2S2_MCK"),
        MTK_FUNCTION(7, "DBG_MON_A_29_")
    ),
    MTK_PIN(
        PINCTRL_PIN(144, "GPIO144"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"4),
        MTK_FUNCTION(1, "DPI_D4"),
        MTK_FUNCTION(2, "NALE"),
        MTK_FUNCTION(3, "UCTS1"),
        MTK_FUNCTION(4, "TDD_TMS"),
        MTK_FUNCTION(5, "I2S2_DI_1"),
        MTK_FUNCTION(7, "DBG_MON_A_30_")
    ),
    MTK_PIN(
        PINCTRL_PIN(145, "GPIO145"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"5),
        MTK_FUNCTION(1, "DPI_D5"),
        MTK_FUNCTION(2, "NCLE"),
        MTK_FUNCTION(3, "URTS1"),
        MTK_FUNCTION(4, "TDD_TCK"),
        MTK_FUNCTION(5, "I2S2_DI_2"),
        MTK_FUNCTION(7, "DBG_MON_A_31_")
    ),
    MTK_PIN(
        PINCTRL_PIN(146, "GPIO146"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"6),
        MTK_FUNCTION(1, "DPI_D6"),
        MTK_FUNCTION(2, "NLD8"),
        MTK_FUNCTION(3, "UTXD2"),
        MTK_FUNCTION(4, "TDD_TDI"),
        MTK_FUNCTION(7, "DBG_MON_A_32_")
    ),
    MTK_PIN(
        PINCTRL_PIN(147, "GPIO147"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"7),
        MTK_FUNCTION(1, "DPI_D7"),
        MTK_FUNCTION(2, "NLD9"),
        MTK_FUNCTION(3, "URXD2"),
        MTK_FUNCTION(4, "TDD_TDO"),
        MTK_FUNCTION(5, "I2S1_WS"),
        MTK_FUNCTION(7, "DBG_MON_B_0_")
    ),
    MTK_PIN(
        PINCTRL_PIN(148, "GPIO148"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"8),
        MTK_FUNCTION(1, "DPI_D8"),
        MTK_FUNCTION(2, "NLD10"),
        MTK_FUNCTION(3, "UCTS2"),
        MTK_FUNCTION(4, "TDD_TRSTN"),
        MTK_FUNCTION(5, "I2S1_BCK"),
        MTK_FUNCTION(7, "DBG_MON_B_1_")
    ),
    MTK_PIN(
        PINCTRL_PIN(149, "GPIO149"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO14"9),
        MTK_FUNCTION(1, "DPI_D9"),
        MTK_FUNCTION(2, "NLD11"),
        MTK_FUNCTION(3, "URTS2"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TMS"),
        MTK_FUNCTION(5, "I2S1_MCK"),
        MTK_FUNCTION(7, "DBG_MON_B_2_")
    ),
    MTK_PIN(
        PINCTRL_PIN(150, "GPIO150"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"0),
        MTK_FUNCTION(1, "DPI_D10"),
        MTK_FUNCTION(2, "NLD12"),
        MTK_FUNCTION(3, "UTXD3"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TCK"),
        MTK_FUNCTION(5, "I2S1_DO_1"),
        MTK_FUNCTION(7, "DBG_MON_B_3_")
    ),
    MTK_PIN(
        PINCTRL_PIN(151, "GPIO151"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"1),
        MTK_FUNCTION(1, "DPI_D11"),
        MTK_FUNCTION(2, "NLD13"),
        MTK_FUNCTION(3, "URXD3"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TDI"),
        MTK_FUNCTION(5, "I2S1_DO_2"),
        MTK_FUNCTION(7, "DBG_MON_B_4_")
    ),
    MTK_PIN(
        PINCTRL_PIN(152, "GPIO152"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"2),
        MTK_FUNCTION(1, "DPI_HSYNC"),
        MTK_FUNCTION(2, "NLD14"),
        MTK_FUNCTION(3, "UCTS3"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TDO"),
        MTK_FUNCTION(5, "DSI1_TE"),
        MTK_FUNCTION(7, "DBG_MON_B_5_")
    ),
    MTK_PIN(
        PINCTRL_PIN(153, "GPIO153"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"3),
        MTK_FUNCTION(1, "DPI_VSYNC"),
        MTK_FUNCTION(2, "NLD15"),
        MTK_FUNCTION(3, "URTS3"),
        MTK_FUNCTION(4, "LTE_MD32_JTAG_TRST"),
        MTK_FUNCTION(5, "DISP_PWM1"),
        MTK_FUNCTION(7, "DBG_MON_B_6_")
    ),
    MTK_PIN(
        PINCTRL_PIN(154, "GPIO154"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"4),
        MTK_FUNCTION(1, "MSDC0_DAT0"),
        MTK_FUNCTION(2, "NLD8"),
        MTK_FUNCTION(7, "DBG_MON_B_7_")
    ),
    MTK_PIN(
        PINCTRL_PIN(155, "GPIO155"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"5),
        MTK_FUNCTION(1, "MSDC0_DAT1"),
        MTK_FUNCTION(2, "NLD9"),
        MTK_FUNCTION(7, "DBG_MON_B_8_")
    ),
    MTK_PIN(
        PINCTRL_PIN(156, "GPIO156"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"6),
        MTK_FUNCTION(1, "MSDC0_DAT2"),
        MTK_FUNCTION(2, "NLD10"),
        MTK_FUNCTION(7, "DBG_MON_B_9_")
    ),
    MTK_PIN(
        PINCTRL_PIN(157, "GPIO157"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"7),
        MTK_FUNCTION(1, "MSDC0_DAT3"),
        MTK_FUNCTION(2, "NLD11"),
        MTK_FUNCTION(7, "DBG_MON_B_10_")
    ),
    MTK_PIN(
        PINCTRL_PIN(158, "GPIO158"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"8),
        MTK_FUNCTION(1, "MSDC0_DAT4"),
        MTK_FUNCTION(2, "NLD12"),
        MTK_FUNCTION(7, "DBG_MON_B_11_")
    ),
    MTK_PIN(
        PINCTRL_PIN(159, "GPIO159"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO15"9),
        MTK_FUNCTION(1, "MSDC0_DAT5"),
        MTK_FUNCTION(2, "NLD13"),
        MTK_FUNCTION(7, "DBG_MON_B_12_")
    ),
    MTK_PIN(
        PINCTRL_PIN(160, "GPIO160"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"0),
        MTK_FUNCTION(1, "MSDC0_DAT6"),
        MTK_FUNCTION(2, "NLD14"),
        MTK_FUNCTION(7, "DBG_MON_B_13_")
    ),
    MTK_PIN(
        PINCTRL_PIN(161, "GPIO161"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"1),
        MTK_FUNCTION(1, "MSDC0_DAT7"),
        MTK_FUNCTION(2, "NLD15"),
        MTK_FUNCTION(7, "DBG_MON_B_14_")
    ),
    MTK_PIN(
        PINCTRL_PIN(162, "GPIO162"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"2),
        MTK_FUNCTION(1, "MSDC0_CMD"),
        MTK_FUNCTION(7, "DBG_MON_B_15_")
    ),
    MTK_PIN(
        PINCTRL_PIN(163, "GPIO163"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"3),
        MTK_FUNCTION(1, "MSDC0_CLK"),
        MTK_FUNCTION(7, "DBG_MON_B_16_")
    ),
    MTK_PIN(
        PINCTRL_PIN(164, "GPIO164"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"4),
        MTK_FUNCTION(1, "MSDC0_DSL"),
        MTK_FUNCTION(7, "DBG_MON_B_17_")
    ),
    MTK_PIN(
        PINCTRL_PIN(165, "GPIO165"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"5),
        MTK_FUNCTION(1, "MSDC0_RSTB"),
        MTK_FUNCTION(7, "DBG_MON_B_18_")
    ),
    MTK_PIN(
        PINCTRL_PIN(166, "GPIO166"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"6),
        MTK_FUNCTION(1, "SPI_CK_0_"),
        MTK_FUNCTION(3, "PWM0"),
        MTK_FUNCTION(7, "DBG_MON_B_19_")
    ),
    MTK_PIN(
        PINCTRL_PIN(167, "GPIO167"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"7),
        MTK_FUNCTION(1, "SPI_MI_0_"),
        MTK_FUNCTION(3, "PWM1"),
        MTK_FUNCTION(4, "SPI_MO_0_"),
        MTK_FUNCTION(7, "DBG_MON_B_20_")
    ),
    MTK_PIN(
        PINCTRL_PIN(168, "GPIO168"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"8),
        MTK_FUNCTION(1, "SPI_MO_0_"),
        MTK_FUNCTION(2, "MD_EINT3"),
        MTK_FUNCTION(3, "PWM2"),
        MTK_FUNCTION(4, "SPI_MI_0_"),
        MTK_FUNCTION(7, "DBG_MON_B_21_")
    ),
    MTK_PIN(
        PINCTRL_PIN(169, "GPIO169"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO16"9),
        MTK_FUNCTION(1, "SPI_CS_0_"),
        MTK_FUNCTION(2, "MD_EINT4"),
        MTK_FUNCTION(3, "PWM3"),
        MTK_FUNCTION(7, "DBG_MON_B_22_")
    ),
    MTK_PIN(
        PINCTRL_PIN(170, "GPIO170"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"0),
        MTK_FUNCTION(1, "MSDC1_CMD"),
        MTK_FUNCTION(7, "DBG_MON_B_23_")
    ),
    MTK_PIN(
        PINCTRL_PIN(171, "GPIO171"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"1),
        MTK_FUNCTION(1, "MSDC1_DAT0"),
        MTK_FUNCTION(7, "DBG_MON_B_24_")
    ),
    MTK_PIN(
        PINCTRL_PIN(172, "GPIO172"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"2),
        MTK_FUNCTION(1, "MSDC1_DAT1"),
        MTK_FUNCTION(7, "DBG_MON_B_25_")
    ),
    MTK_PIN(
        PINCTRL_PIN(173, "GPIO173"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"3),
        MTK_FUNCTION(1, "MSDC1_DAT2"),
        MTK_FUNCTION(7, "DBG_MON_B_26_")
    ),
    MTK_PIN(
        PINCTRL_PIN(174, "GPIO174"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"4),
        MTK_FUNCTION(1, "MSDC1_DAT3"),
        MTK_FUNCTION(7, "DBG_MON_B_27_")
    ),
    MTK_PIN(
        PINCTRL_PIN(175, "GPIO175"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"5),
        MTK_FUNCTION(1, "MSDC1_CLK"),
        MTK_FUNCTION(7, "DBG_MON_B_28_")
    ),
    MTK_PIN(
        PINCTRL_PIN(176, "GPIO176"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"6),
        MTK_FUNCTION(1, "PWRAP_SPIMI"),
        MTK_FUNCTION(2, "PWRAP_SPIMO")
    ),
    MTK_PIN(
        PINCTRL_PIN(177, "GPIO177"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"7),
        MTK_FUNCTION(1, "PWRAP_SPIMO"),
        MTK_FUNCTION(2, "PWRAP_SPIMI")
    ),
    MTK_PIN(
        PINCTRL_PIN(178, "GPIO178"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"8),
        MTK_FUNCTION(1, "PWRAP_SPICK")
    ),
    MTK_PIN(
        PINCTRL_PIN(179, "GPIO179"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO17"9),
        MTK_FUNCTION(1, "PWRAP_SPICS")
    ),
    MTK_PIN(
        PINCTRL_PIN(180, "GPIO180"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"0),
        MTK_FUNCTION(1, "AUD_CLK_MOSI"),
        MTK_FUNCTION(2, "I2S1_WS"),
        MTK_FUNCTION(3, "I2S2_WS"),
        MTK_FUNCTION(4, "I2S0_WS")
    ),
    MTK_PIN(
        PINCTRL_PIN(181, "GPIO181"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"1),
        MTK_FUNCTION(1, "AUD_DAT_MISO_1"),
        MTK_FUNCTION(2, "I2S1_BCK"),
        MTK_FUNCTION(3, "I2S2_BCK"),
        MTK_FUNCTION(4, "I2S0_BCK")
    ),
    MTK_PIN(
        PINCTRL_PIN(182, "GPIO182"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"2),
        MTK_FUNCTION(1, "AUD_DAT_MOSI_1"),
        MTK_FUNCTION(2, "I2S1_MCK"),
        MTK_FUNCTION(3, "I2S2_MCK"),
        MTK_FUNCTION(4, "I2S0_MCK")
    ),
    MTK_PIN(
        PINCTRL_PIN(183, "GPIO183"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"3),
        MTK_FUNCTION(1, "AUD_DAT_MISO_2"),
        MTK_FUNCTION(2, "I2S1_DO_1"),
        MTK_FUNCTION(3, "I2S2_DI_1"),
        MTK_FUNCTION(4, "I2S0_DO"),
        MTK_FUNCTION(7, "DBG_MON_B_29_")
    ),
    MTK_PIN(
        PINCTRL_PIN(184, "GPIO184"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"4),
        MTK_FUNCTION(1, "AUD_DAT_MOSI_2"),
        MTK_FUNCTION(2, "I2S1_DO_2"),
        MTK_FUNCTION(3, "I2S2_DI_2"),
        MTK_FUNCTION(4, "I2S0_DI"),
        MTK_FUNCTION(7, "DBG_MON_B_30_")
    ),
    MTK_PIN(
        PINCTRL_PIN(185, "GPIO185"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"5),
        MTK_FUNCTION(1, "RTC32K_CK")
    ),
    MTK_PIN(
        PINCTRL_PIN(186, "GPIO186"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"6),
        MTK_FUNCTION(1, "DISP_PWM0"),
        MTK_FUNCTION(2, "DISP_PWM1"),
        MTK_FUNCTION(7, "DBG_MON_B_31_")
    ),
    MTK_PIN(
        PINCTRL_PIN(187, "GPIO187"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"7),
        MTK_FUNCTION(1, "SRCLKENAI")
    ),
    MTK_PIN(
        PINCTRL_PIN(188, "GPIO188"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"8),
        MTK_FUNCTION(1, "SRCLKENAI2")
    ),
    MTK_PIN(
        PINCTRL_PIN(189, "GPIO189"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO18"9),
        MTK_FUNCTION(1, "SRCLKENA0")
    ),
    MTK_PIN(
        PINCTRL_PIN(190, "GPIO190"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"0),
        MTK_FUNCTION(1, "SRCLKENA1")
    ),
    MTK_PIN(
        PINCTRL_PIN(191, "GPIO191"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"1),
        MTK_FUNCTION(1, "WATCHDOG_AO")
    ),
    MTK_PIN(
        PINCTRL_PIN(192, "GPIO192"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"2),
        MTK_FUNCTION(1, "I2S0_WS"),
        MTK_FUNCTION(2, "I2S1_WS"),
        MTK_FUNCTION(3, "I2S2_WS"),
        MTK_FUNCTION(4, "NCEB1"),
        MTK_FUNCTION(7, "DBG_MON_A_4_")
    ),
    MTK_PIN(
        PINCTRL_PIN(193, "GPIO193"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"3),
        MTK_FUNCTION(1, "I2S0_BCK"),
        MTK_FUNCTION(2, "I2S1_BCK"),
        MTK_FUNCTION(3, "I2S2_BCK"),
        MTK_FUNCTION(4, "NRNB1"),
        MTK_FUNCTION(7, "DBG_MON_A_5_")
    ),
    MTK_PIN(
        PINCTRL_PIN(194, "GPIO194"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"4),
        MTK_FUNCTION(1, "I2S0_MCK"),
        MTK_FUNCTION(2, "I2S1_MCK"),
        MTK_FUNCTION(3, "I2S2_MCK"),
        MTK_FUNCTION(7, "DBG_MON_A_6_")
    ),
    MTK_PIN(
        PINCTRL_PIN(195, "GPIO195"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"5),
        MTK_FUNCTION(1, "I2S0_DO"),
        MTK_FUNCTION(2, "I2S1_DO_1"),
        MTK_FUNCTION(3, "I2S2_DI_1"),
        MTK_FUNCTION(7, "DBG_MON_A_7_")
    ),
    MTK_PIN(
        PINCTRL_PIN(196, "GPIO196"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(0, "GPIO19"6),
        MTK_FUNCTION(1, "I2S0_DI"),
        MTK_FUNCTION(2, "I2S1_DO_2"),
        MTK_FUNCTION(3, "I2S2_DI_2"),
        MTK_FUNCTION(7, "DBG_MON_A_8_")
    ),
    MTK_PIN(
        PINCTRL_PIN(197, "GPIO197"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT2")
    ),
    MTK_PIN(
        PINCTRL_PIN(198, "GPIO198"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT3")
    ),
    MTK_PIN(
        PINCTRL_PIN(199, "GPIO199"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT4")
    ),
    MTK_PIN(
        PINCTRL_PIN(200, "GPIO200"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT5")
    ),
    MTK_PIN(
        PINCTRL_PIN(201, "GPIO201"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT6")
    ),
    MTK_PIN(
        PINCTRL_PIN(202, "GPIO202"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT7")
    ),
    MTK_PIN(
        PINCTRL_PIN(203, "GPIO203"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT8"),
        MTK_FUNCTION(2, "CMCSD3")
    ),
    MTK_PIN(
        PINCTRL_PIN(204, "GPIO204"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT9"),
        MTK_FUNCTION(2, "CMCSD2")
    ),
    MTK_PIN(
        PINCTRL_PIN(205, "GPIO205"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMHSYNC"),
        MTK_FUNCTION(2, "CMCSD1")
    ),
    MTK_PIN(
        PINCTRL_PIN(206, "GPIO206"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMVSYNC"),
        MTK_FUNCTION(2, "CMCSD0")
    ),
    MTK_PIN(
        PINCTRL_PIN(207, "GPIO207"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT)
    ),
    MTK_PIN(
        PINCTRL_PIN(208, "GPIO208"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT)
    ),
    MTK_PIN(
        PINCTRL_PIN(209, "GPIO209"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT1")
    ),
    MTK_PIN(
        PINCTRL_PIN(210, "GPIO210"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
        MTK_FUNCTION(1, "CMDAT0")
    ),
    MTK_PIN(
        PINCTRL_PIN(211, "GPIO211"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT)
    ),
    MTK_PIN(
        PINCTRL_PIN(212, "GPIO212"),
        NULL, "mt6595",
        MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT)
    )
};

#endif /* __PINCTRL_MTK_MT6580_H */